import { useAuth } from '@/src/context/AuthContext';
import {
  CustomOrderField,
  getClientCustomOrdersRealtime,
  getOrderTraceability,
} from '@/src/firebase/orderService';
import { Ionicons } from '@expo/vector-icons';
import * as FileSystem from 'expo-file-system';
import { useRouter } from 'expo-router';
import * as Sharing from 'expo-sharing';
import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  Firestore,
  getDocs,
  getFirestore,
  limit,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  where,
} from 'firebase/firestore';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  FlatList,
  Image,
  Modal,
  Pressable,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface Invoice {
  id: string;
  orderId: string;
  orderType: 'ticket' | 'service';
  userId: string;
  downloadURL?: string;
  createdAt: string;
  amount: number;
  currency: string;
  status: string;
  autoGenerated?: boolean;
  invoiceNumber?: string;
  artistName?: string;
  title?: string;
}

interface Order {
  id: string;
  title: string;
  description: string;
  createdAt: string;
  status: OrderStatus;
  orderType: 'ticket' | 'service';
  amount: number;
  currency: string;
  clientId: string;
  artistId?: string;
  artistName?: string;
  cover?: string;
  image?: string;
  coverImage?: string;
  imageUrl?: string;
  serviceCover?: string;
  items?: Array<{ name: string; qty: number; price: number }>;
  paymentStatus?: 'unpaid' | 'paid' | 'refunded';
  paymentMethod?: string;
  notes?: string;
}

interface AppNotification {
  id: string;
  orderId?: string;
  orderType?: 'ticket' | 'service';
  status?: string;
  title: string;
  message: string;
  icon: string;
  createdAt: string;
  isRead: boolean;
  type: 'celebration' | 'promo' | 'info' | 'reminder' | 'order_status';
}

interface TraceStep {
  id: string;
  status: string;
  title: string;
  body: string;
  isRead: boolean;
  createdAt: string;
  artistId: string;
  artistName: string;
  displayLabel: string;
}

interface ServiceOrderWithMeta extends CustomOrderField {
  artistName?: string;
  createdAt: string;
}

type OrderStatus =
  | 'pending'
  | 'accepted'
  | 'confirmed'
  | 'declined'
  | 'rejected'
  | 'completed'
  | 'cancelled';

type TabType = 'orders' | 'custom' | 'invoices';

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

const STATUS_LABEL: Record<OrderStatus, string> = {
  pending: 'Waiting for artist',
  accepted: 'Approved',
  confirmed: 'Confirmed',
  declined: 'Declined',
  rejected: 'Rejected',
  completed: 'Completed',
  cancelled: 'Cancelled',
};

const STATUS_COLOR: Record<OrderStatus, string> = {
  pending: '#ca8a04',
  accepted: '#16a34a',
  confirmed: '#16a34a',
  declined: '#dc2626',
  rejected: '#dc2626',
  completed: '#2563eb',
  cancelled: '#6b7280',
};

const STATUS_ICON: Record<OrderStatus, keyof typeof Ionicons.glyphMap> = {
  pending: 'time-outline',
  accepted: 'checkmark-circle-outline',
  confirmed: 'checkmark-done-outline',
  declined: 'close-circle-outline',
  rejected: 'close-circle-outline',
  completed: 'trophy-outline',
  cancelled: 'ban-outline',
};

// Statuses that trigger automatic invoice generation.
const INVOICE_TRIGGER_STATUSES: OrderStatus[] = ['confirmed', 'accepted', 'completed'];

// ─────────────────────────────────────────────────────────────────────────────
// Pure helpers (no React)
// ─────────────────────────────────────────────────────────────────────────────

function normalizeDate(raw: any): string {
  if (!raw) return new Date().toISOString();
  if (typeof raw === 'string') return raw;
  if (typeof raw?.toDate === 'function') return raw.toDate().toISOString();
  if (raw instanceof Date) return raw.toISOString();
  if (typeof raw === 'number') return new Date(raw).toISOString();
  return new Date().toISOString();
}

function timeAgo(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 30) return `${days}d ago`;
  const months = Math.floor(days / 30);
  return `${months}mo ago`;
}

function money(n?: number): string {
  if (n == null || isNaN(Number(n))) return '—';
  return Number(n).toLocaleString(undefined, { maximumFractionDigits: 2 });
}

function getOrderCover(order: any): string | undefined {
  return (
    order.cover ||
    order.image ||
    order.coverImage ||
    order.imageUrl ||
    order.serviceCover ||
    order.serviceImage ||
    order.thumbnail
  );
}

function formatLongDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function formatShortDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

function shortId(id: string): string {
  return id.substring(0, 8).toUpperCase();
}

async function fetchArtistNames(
  db: Firestore,
  artistIds: string[],
): Promise<Record<string, string>> {
  const uniqueIds = [...new Set(artistIds.filter(Boolean))];
  if (!uniqueIds.length) return {};

  const map: Record<string, string> = {};
  try {
    const snap = await getDocs(collection(db, 'users'));
    for (const dc of snap.docs) {
      const d = dc.data() as any;
      if (d.role === 'artist' || d.type === 'artist') {
        map[dc.id] = d.storeName || d.name || d.displayName || `Artist ${dc.id.slice(0, 6)}`;
      }
    }
  } catch (err) {
    console.warn('fetchArtistNames: failed to list users', err);
  }
  for (const uid of uniqueIds) {
    if (!map[uid]) map[uid] = `Artist ${uid.slice(0, 6)}`;
  }
  return map;
}

/**
 * Creates an invoice for an order, but only if one doesn't already exist.
 *
 * IMPORTANT: this is a client-side stop-gap. The proper place for this is a
 * Cloud Function triggered on `orders/{orderId}` status change — that's the
 * only way to guarantee single-source-of-truth invoice generation, generate
 * a real PDF, and avoid race conditions between multiple online clients.
 */
async function ensureInvoiceForOrder(
  db: Firestore,
  params: {
    orderId: string;
    orderType: 'ticket' | 'service';
    userId: string;
    amount: number;
    currency: string;
    artistName?: string;
    title?: string;
  },
): Promise<{ created: boolean; invoiceId?: string }> {
  if (!params.userId || !params.orderId) return { created: false };
  if (!params.amount || params.amount <= 0) return { created: false };

  try {
    // Dedup guard: bail if any invoice already references this order.
    const existing = await getDocs(
      query(
        collection(db, 'invoices'),
        where('orderId', '==', params.orderId),
        limit(1),
      ),
    );
    if (!existing.empty) return { created: false, invoiceId: existing.docs[0].id };

    const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}-${shortId(params.orderId)}`;
    const ref = await addDoc(collection(db, 'invoices'), {
      orderId: params.orderId,
      orderType: params.orderType,
      userId: params.userId,
      amount: params.amount,
      currency: params.currency || 'MAD',
      status: 'issued',
      invoiceNumber,
      title: params.title || '',
      artistName: params.artistName || '',
      autoGenerated: true,
      // downloadURL intentionally omitted — populated by a server function
      // that renders the PDF and uploads it to Firebase Storage.
      downloadURL: '',
      createdAt: serverTimestamp(),
    });
    return { created: true, invoiceId: ref.id };
  } catch (err) {
    console.error('ensureInvoiceForOrder failed:', err);
    return { created: false };
  }
}

function buildTimeline(
  steps: TraceStep[],
  orderCreatedAt: string,
): Array<{ date: string; label: string; artistName: string; time: string; color: string }> {
  const seen = new Set<string>();
  const timeline: Array<{ date: string; label: string; artistName: string; time: string; color: string }> = [];

  const push = (d: { date: string; label: string; artistName: string; color: string }) => {
    const key = `${d.date}|${d.label}|${d.artistName}`;
    if (!seen.has(key)) {
      seen.add(key);
      timeline.push({ ...d, time: '' });
    }
  };

  push({
    date: formatLongDate(orderCreatedAt),
    label: 'Order placed',
    artistName: 'You',
    color: '#6366f1',
  });

  for (const s of steps) {
    const status = (s.status as OrderStatus) in STATUS_COLOR ? (s.status as OrderStatus) : 'pending';
    push({
      date: formatLongDate(s.createdAt),
      label: s.displayLabel || STATUS_LABEL[status],
      artistName: s.artistName,
      color: STATUS_COLOR[status],
    });
    timeline[timeline.length - 1].time = timeAgo(s.createdAt);
  }

  return timeline;
}

// ─────────────────────────────────────────────────────────────────────────────
// Invoice download / share
// ─────────────────────────────────────────────────────────────────────────────

async function downloadAndSaveInvoice(url: string, filename: string): Promise<void> {
  try {
    const dir = FileSystem.documentDirectory;
    if (!dir) { Alert.alert('Error', 'Cannot access file system.'); return; }
    await FileSystem.downloadAsync(url, dir + filename);
    Alert.alert('Saved', `"${filename}" saved to your files.`);
  } catch (err) {
    console.error('downloadAndSaveInvoice failed:', err);
    Alert.alert('Error', 'Failed to download invoice.');
  }
}

async function shareInvoiceFile(url: string, filename: string): Promise<void> {
  try {
    const dir = FileSystem.cacheDirectory;
    if (!dir) { Alert.alert('Error', 'Cache directory unavailable.'); return; }
    await FileSystem.downloadAsync(url, dir + filename);
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) await Sharing.shareAsync(dir + filename);
    else Alert.alert('Unavailable', 'Sharing is not supported on this device.');
  } catch (err) {
    console.error('shareInvoiceFile failed:', err);
    Alert.alert('Error', 'Failed to share invoice.');
  }
}

function openInvoiceActions(invoice: Invoice): void {
  if (!invoice.downloadURL) {
    Alert.alert(
      'Invoice Pending',
      'This invoice has been generated but the PDF is still being prepared. Please try again in a moment.',
    );
    return;
  }
  const filename = `invoice_${invoice.invoiceNumber || invoice.id}.pdf`;
  Alert.alert(
    `Invoice ${invoice.invoiceNumber || shortId(invoice.id)}`,
    'Download or share this invoice?',
    [
      { text: 'Download', onPress: () => downloadAndSaveInvoice(invoice.downloadURL!, filename) },
      { text: 'Share', onPress: () => shareInvoiceFile(invoice.downloadURL!, filename) },
      { text: 'Cancel', style: 'cancel' },
    ],
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc', paddingHorizontal: 14, paddingTop: 10 },

  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 12, fontSize: 15, color: '#6366f1', fontWeight: '500' },

  listContainer: { paddingBottom: 40 },

  // ── Summary header ───────────────────────────────────────────────────────
  summaryRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  summaryCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  summaryLabel: { fontSize: 10, color: '#6b7280', fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.4 },
  summaryValue: { fontSize: 20, fontWeight: '800', color: '#111827', marginTop: 4 },
  summaryUnit: { fontSize: 10, color: '#6b7280', fontWeight: '500', marginTop: 2 },

  // ── Tabs ─────────────────────────────────────────────────────────────────
  tabRow: {
    flexDirection: 'row',
    marginBottom: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e0e7ff',
    backgroundColor: '#eef2ff',
    padding: 3,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 6,
    borderRadius: 11,
  },
  tabButtonActive: { backgroundColor: '#6366f1' },
  tabLabel: { fontSize: 12, fontWeight: '600', color: '#6366f1' },
  tabLabelActive: { color: '#ffffff' },
  tabBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  tabBadgeText: { fontSize: 10, fontWeight: '700', color: '#6366f1' },
  tabBadgeTextActive: { color: '#6366f1' },

  // ── Card (shared) ────────────────────────────────────────────────────────
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#eef2f7',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  orderCover: {
    width: '100%',
    height: 170,
    borderRadius: 14,
    marginBottom: 12,
    backgroundColor: '#e2e8f0',
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#0f172a', marginBottom: 2 },
  cardId: { fontSize: 10, fontWeight: '700', color: '#94a3b8', letterSpacing: 0.6, marginBottom: 4 },
  artistName: { fontSize: 12.5, fontWeight: '600', color: '#5b5bd6', marginBottom: 2 },
  cardSub: { fontSize: 13, color: '#475569', marginBottom: 4, lineHeight: 18 },
  cardDate: { fontSize: 11.5, color: '#94a3b8' },

  amountBox: {
    alignItems: 'flex-end',
    backgroundColor: '#f0f9ff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  amountText: { fontSize: 15, fontWeight: '800', color: '#0369a1' },
  amountCurrency: { fontSize: 10, color: '#0369a1', fontWeight: '600' },
  amountLabel: { marginTop: 4, fontSize: 11, fontWeight: '700', color: '#475569' },

  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },

  // ── Status pill (now with icon) ──────────────────────────────────────────
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    gap: 4,
  },
  statusPillText: { fontSize: 11.5, fontWeight: '700' },

  // ── Paid badge ───────────────────────────────────────────────────────────
  paidBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: '#dcfce7',
    marginLeft: 6,
  },
  paidBadgeText: { fontSize: 10, fontWeight: '700', color: '#15803d' },

  // ── Action buttons ───────────────────────────────────────────────────────
  actionsRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  ghostButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  ghostButtonText: { fontSize: 12, fontWeight: '600', color: '#5b5bd6' },

  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6366f1',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    gap: 6,
  },
  downloadButtonText: { color: '#ffffff', fontSize: 13, fontWeight: '700' },

  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
    gap: 4,
  },
  deleteButtonText: { color: '#b91c1c', fontSize: 12, fontWeight: '700' },

  // ── Expanded details ─────────────────────────────────────────────────────
  detailsBlock: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 8,
  },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  detailLabel: { fontSize: 12, color: '#64748b', fontWeight: '600' },
  detailValue: { fontSize: 12.5, color: '#0f172a', fontWeight: '600', flex: 1, textAlign: 'right' },

  itemsList: { marginTop: 4, gap: 6 },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
  },
  itemText: { fontSize: 12, color: '#334155' },
  itemPrice: { fontSize: 12, fontWeight: '700', color: '#0f172a' },

  // ── Traceability timeline ────────────────────────────────────────────────
  traceContainer: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#e5e7eb' },
  traceSectionHeader: { marginBottom: 12 },
  traceSectionTitle: { fontSize: 14, fontWeight: '700', color: '#1f2937', marginBottom: 2 },
  traceSectionSub: { fontSize: 11.5, color: '#6b7280', lineHeight: 16 },

  timelineRow: { flexDirection: 'row' },
  timelineLeft: { width: 78, alignItems: 'flex-end', paddingRight: 8 },
  timelineDateText: { fontSize: 10.5, color: '#64748b', fontWeight: '600' },
  timelineMid: { alignItems: 'center', width: 18 },
  timelineDot: { width: 10, height: 10, borderRadius: 5, marginTop: 3, zIndex: 1, borderWidth: 2, borderColor: '#fff' },
  timelineLine: { width: 2, flex: 1, backgroundColor: '#e2e8f0', minHeight: 24 },
  timelineRight: { flex: 1, paddingBottom: 14, paddingLeft: 8 },
  timelineStepLabel: { fontSize: 13, fontWeight: '700', color: '#0f172a', marginBottom: 2 },
  timelineActor: { fontSize: 11.5, color: '#64748b' },
  timelineActorTime: { fontSize: 10.5, color: '#94a3b8', marginLeft: 4 },

  // ── Empty states ─────────────────────────────────────────────────────────
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40, marginTop: 50 },
  emptyIcon: { fontSize: 54, marginBottom: 12 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#374151', marginBottom: 8, textAlign: 'center' },
  emptyText: { fontSize: 13, color: '#9ca3af', textAlign: 'center', lineHeight: 20 },

  // ── Auto-invoice toast indicator ─────────────────────────────────────────
  autoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: '#fef3c7',
    borderRadius: 6,
  },
  autoBadgeText: { fontSize: 9, fontWeight: '700', color: '#92400e', letterSpacing: 0.3 },
});

// ─────────────────────────────────────────────────────────────────────────────
// Sub-components
// ─────────────────────────────────────────────────────────────────────────────

function StatusBadge({ status }: { status: OrderStatus }) {
  const color = STATUS_COLOR[status];
  const label = STATUS_LABEL[status];
  const icon = STATUS_ICON[status];
  return (
    <View style={[styles.statusPill, { backgroundColor: `${color}1A`, borderColor: `${color}55` }]}>
      <Ionicons name={icon} size={12} color={color} />
      <Text style={[styles.statusPillText, { color }]}>{label}</Text>
    </View>
  );
}

function TimelineRow({
  label, artistName, time, isLast, date, color,
}: {
  label: string; artistName: string; time: string; isLast: boolean; date: string; color: string;
}) {
  return (
    <View style={styles.timelineRow}>
      <View style={styles.timelineLeft}>
        <Text style={styles.timelineDateText}>{date}</Text>
      </View>
      <View style={styles.timelineMid}>
        <View style={[styles.timelineDot, { backgroundColor: color }]} />
        {!isLast && <View style={styles.timelineLine} />}
      </View>
      <View style={styles.timelineRight}>
        <Text style={styles.timelineStepLabel}>{label}</Text>
        <Text style={styles.timelineActor}>
          by {artistName}
          {time ? <Text style={styles.timelineActorTime}>  {time}</Text> : null}
        </Text>
      </View>
    </View>
  );
}

function TraceabilitySection({
  steps, orderCreatedAt, serviceName,
}: {
  steps: TraceStep[]; orderCreatedAt: string; serviceName: string;
}) {
  const timeline = useMemo(
    () => buildTimeline(steps, orderCreatedAt),
    [steps, orderCreatedAt],
  );

  return (
    <View style={styles.traceContainer}>
      <View style={styles.traceSectionHeader}>
        <Text style={styles.traceSectionTitle}>📜 Order History — {serviceName}</Text>
        <Text style={styles.traceSectionSub}>
          Every status change with timestamp and who performed it.
        </Text>
      </View>
      <View>
        {timeline.map((t, i) => (
          <TimelineRow
            key={`${t.date}|${t.label}|${i}`}
            label={t.label}
            artistName={t.artistName}
            time={t.time}
            date={t.date}
            color={t.color}
            isLast={i === timeline.length - 1}
          />
        ))}
      </View>
    </View>
  );
}

function SummaryHeader({
  totalSpent,
  pendingCount,
  completedCount,
}: { totalSpent: number; pendingCount: number; completedCount: number }) {
  return (
    <View style={styles.summaryRow}>
      <View style={styles.summaryCard}>
        <Text style={styles.summaryLabel}>Spent</Text>
        <Text style={styles.summaryValue}>{money(totalSpent)}</Text>
        <Text style={styles.summaryUnit}>MAD total</Text>
      </View>
      <View style={styles.summaryCard}>
        <Text style={styles.summaryLabel}>Pending</Text>
        <Text style={[styles.summaryValue, { color: '#ca8a04' }]}>{pendingCount}</Text>
        <Text style={styles.summaryUnit}>awaiting</Text>
      </View>
      <View style={styles.summaryCard}>
        <Text style={styles.summaryLabel}>Done</Text>
        <Text style={[styles.summaryValue, { color: '#16a34a' }]}>{completedCount}</Text>
        <Text style={styles.summaryUnit}>completed</Text>
      </View>
    </View>
  );
}

function CustomOrderCard({
  item, traceSteps, onToggleTrace, onDelete, showTrace, expanded, onToggleExpand,
}: {
  item: ServiceOrderWithMeta;
  traceSteps: TraceStep[];
  onToggleTrace: (orderId: string) => void;
  onDelete: () => void;
  showTrace: boolean;
  expanded: boolean;
  onToggleExpand: () => void;
}) {
  const date = formatShortDate(item.createdAt);
  const status = (((item as any).status || (item as any).orderStatus || 'pending') as OrderStatus);
  const color = STATUS_COLOR[status] ?? STATUS_COLOR.pending;
  const message: string | undefined = (item as any).message;
  const coverImage = getOrderCover(item as any);
  const priceLabel = 'Final price';

  return (
    <View style={styles.card}>
      {coverImage ? (
        <Image source={{ uri: coverImage }} style={styles.orderCover} />
      ) : null}
      <Pressable onPress={onToggleExpand}>
        <View style={styles.cardHeader}>
          <View style={[styles.iconCircle, { backgroundColor: `${color}1A` }]}>
            <Ionicons name="construct-outline" size={22} color={color} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.cardId}>#{shortId(item.id)}</Text>
            <Text style={styles.cardTitle}>{(item as any).serviceName || 'Service Request'}</Text>
            {item.artistName ? <Text style={styles.artistName}>{item.artistName}</Text> : null}
            <Text style={styles.cardDate}>{date}</Text>
          </View>
          <View style={styles.amountBox}>
            <Text style={styles.amountText}>{money((item as any).clientPrice)}</Text>
            <Text style={styles.amountCurrency}>MAD</Text>
            <Text style={styles.amountLabel}>{priceLabel}</Text>
          </View>
        </View>

        {message ? (
          <Text style={[styles.cardSub, { marginTop: 8 }]} numberOfLines={expanded ? undefined : 2}>
            {message}
          </Text>
        ) : null}
      </Pressable>

      {expanded ? (
        <View style={styles.detailsBlock}>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Order ID</Text>
            <Text style={styles.detailValue} selectable>{item.id}</Text>
          </View>
          {(item as any).artistPrice != null ? (
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Artist quote</Text>
              <Text style={styles.detailValue}>{money((item as any).artistPrice)} MAD</Text>
            </View>
          ) : null}
          {(item as any).deadline ? (
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Deadline</Text>
              <Text style={styles.detailValue}>{(item as any).deadline}</Text>
            </View>
          ) : null}
          {(item as any).category ? (
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Category</Text>
              <Text style={styles.detailValue}>{(item as any).category}</Text>
            </View>
          ) : null}
        </View>
      ) : null}

      <View style={styles.cardFooter}>
        <StatusBadge status={status} />
        <View style={styles.actionsRow}>
          <TouchableOpacity
            style={styles.ghostButton}
            onPress={() => onToggleTrace(item.id)}
            activeOpacity={0.7}
          >
            <Ionicons name={showTrace ? 'chevron-up' : 'list-outline'} size={14} color="#5b5bd6" />
            <Text style={styles.ghostButtonText}>{showTrace ? 'Hide' : 'Trace'}</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.deleteButton} onPress={onDelete} activeOpacity={0.7}>
            <Ionicons name="trash-outline" size={14} color="#b91c1c" />
            <Text style={styles.deleteButtonText}>Delete</Text>
          </TouchableOpacity>
        </View>
      </View>

      {showTrace ? (
        <TraceabilitySection
          steps={traceSteps}
          orderCreatedAt={item.createdAt}
          serviceName={(item as any).serviceName || 'Service'}
        />
      ) : null}
    </View>
  );
}

function OrderCard({
  item, onDelete, expanded, onToggleExpand,
}: {
  item: Order; onDelete: () => void; expanded: boolean; onToggleExpand: () => void;
}) {
  const date = formatShortDate(item.createdAt);
  const color = STATUS_COLOR[item.status] ?? STATUS_COLOR.pending;
  const isPaid = item.paymentStatus === 'paid';
  const coverImage = getOrderCover(item);
  const priceLabel = item.orderType === 'service' ? 'Final price' : 'Amount';

  return (
    <View style={styles.card}>
      {coverImage ? (
        <Image source={{ uri: coverImage }} style={styles.orderCover} />
      ) : null}
      <Pressable onPress={onToggleExpand}>
        <View style={styles.cardHeader}>
          <View style={[styles.iconCircle, { backgroundColor: `${color}1A` }]}>
            <Ionicons
              name={item.orderType === 'ticket' ? 'ticket-outline' : 'briefcase-outline'}
              size={22}
              color={color}
            />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={styles.cardId}>#{shortId(item.id)}</Text>
            <Text style={styles.cardTitle}>{item.title || 'Untitled order'}</Text>
            {item.artistName ? <Text style={styles.artistName}>{item.artistName}</Text> : null}
            {item.description ? (
              <Text style={styles.cardSub} numberOfLines={expanded ? undefined : 2}>
                {item.description}
              </Text>
            ) : null}
            <Text style={styles.cardDate}>{date}</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <View style={styles.amountBox}>
              <Text style={styles.amountText}>{money(item.amount)}</Text>
              <Text style={styles.amountCurrency}>{item.currency || 'MAD'}</Text>
              <Text style={styles.amountLabel}>{priceLabel}</Text>
            </View>
            {isPaid ? (
              <View style={styles.paidBadge}>
                <Ionicons name="checkmark-circle" size={10} color="#15803d" />
                <Text style={styles.paidBadgeText}>PAID</Text>
              </View>
            ) : null}
          </View>
        </View>
      </Pressable>

      {expanded ? (
        <View style={styles.detailsBlock}>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Order ID</Text>
            <Text style={styles.detailValue} selectable>{item.id}</Text>
          </View>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Type</Text>
            <Text style={styles.detailValue}>{item.orderType === 'ticket' ? 'Ticket' : 'Service'}</Text>
          </View>
          {item.paymentMethod ? (
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Payment</Text>
              <Text style={styles.detailValue}>{item.paymentMethod}</Text>
            </View>
          ) : null}
          {item.notes ? (
            <View style={styles.detailRow}>
              <Text style={styles.detailLabel}>Notes</Text>
              <Text style={styles.detailValue}>{item.notes}</Text>
            </View>
          ) : null}
          {item.items?.length ? (
            <View style={styles.itemsList}>
              {item.items.map((it, i) => (
                <View key={i} style={styles.itemRow}>
                  <Text style={styles.itemText}>{it.name} × {it.qty}</Text>
                  <Text style={styles.itemPrice}>{money(it.qty * it.price)} {item.currency || 'MAD'}</Text>
                </View>
              ))}
            </View>
          ) : null}
        </View>
      ) : null}

      <View style={styles.cardFooter}>
        <StatusBadge status={item.status} />
        <TouchableOpacity style={styles.deleteButton} onPress={onDelete} activeOpacity={0.7}>
          <Ionicons name="trash-outline" size={14} color="#b91c1c" />
          <Text style={styles.deleteButtonText}>Delete</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

function InvoiceItem({
  item, expanded, onToggleExpand,
}: {
  item: Invoice; expanded: boolean; onToggleExpand: () => void;
}) {
  const date = formatShortDate(item.createdAt);
  const isPending = !item.downloadURL;

  return (
    <View style={styles.card}>
      <Pressable onPress={onToggleExpand}>
        <View style={styles.cardHeader}>
          <View style={[styles.iconCircle, { backgroundColor: '#e0e7ff' }]}>
            <Ionicons name="document-text-outline" size={22} color="#6366f1" />
          </View>
          <View style={{ flex: 1 }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
              <Text style={styles.cardTitle}>{item.invoiceNumber || `INV-${shortId(item.id)}`}</Text>
              {item.autoGenerated ? (
                <View style={styles.autoBadge}>
                  <Ionicons name="flash" size={9} color="#92400e" />
                  <Text style={styles.autoBadgeText}>AUTO</Text>
                </View>
              ) : null}
            </View>
            <Text style={styles.cardDate}>{date}</Text>
            <Text style={styles.cardSub}>
              {item.orderType === 'service' ? '🛍️ Service' : '🎫 Ticket'}
              {item.artistName ? ` · ${item.artistName}` : ''}
            </Text>
          </View>
          <View style={styles.amountBox}>
            <Text style={styles.amountText}>{money(item.amount)}</Text>
            <Text style={styles.amountCurrency}>{item.currency || 'MAD'}</Text>
          </View>
        </View>
      </Pressable>

      {expanded ? (
        <View style={styles.detailsBlock}>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Invoice ID</Text>
            <Text style={styles.detailValue} selectable>{item.id}</Text>
          </View>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Order ref</Text>
            <Text style={styles.detailValue} selectable>{item.orderId}</Text>
          </View>
          <View style={styles.detailRow}>
            <Text style={styles.detailLabel}>Status</Text>
            <Text style={[styles.detailValue, { color: isPending ? '#ca8a04' : '#16a34a' }]}>
              {isPending ? 'PDF generating…' : 'Ready'}
            </Text>
          </View>
        </View>
      ) : null}

      <View style={styles.cardFooter}>
        <View style={[styles.statusPill, {
          backgroundColor: isPending ? '#fef9c3' : '#dcfce7',
          borderColor: isPending ? '#fde68a' : '#86efac',
        }]}>
          <Ionicons
            name={isPending ? 'time-outline' : 'checkmark-circle-outline'}
            size={12}
            color={isPending ? '#ca8a04' : '#15803d'}
          />
          <Text style={[styles.statusPillText, { color: isPending ? '#ca8a04' : '#15803d' }]}>
            {isPending ? 'Generating' : 'Ready'}
          </Text>
        </View>
        <TouchableOpacity
          style={[styles.downloadButton, isPending && { backgroundColor: '#cbd5e1' }]}
          onPress={() => openInvoiceActions(item)}
          activeOpacity={0.7}
        >
          <Ionicons name="download-outline" size={14} color="#fff" />
          <Text style={styles.downloadButtonText}>{isPending ? 'Pending' : 'Download'}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main screen
// ─────────────────────────────────────────────────────────────────────────────

export default function InvoicesScreen() {
  const router = useRouter();
  const { user, loading: authLoading } = useAuth();
  const db = getFirestore();
  const uid = user?.uid;

  const [activeTab, setActiveTab] = useState<TabType>('orders');

  const [allOrders, setAllOrders] = useState<Order[]>([]);
  const [ordersLoading, setOrdersLoading] = useState(true);

  const [clientCustomOrders, setClientCustomOrders] = useState<ServiceOrderWithMeta[]>([]);
  const [customOrdersLoading, setCustomOrdersLoading] = useState(true);
  const [customOrderTraces, setCustomOrderTraces] = useState<Record<string, TraceStep[]>>({});
  const [expandedTraces, setExpandedTraces] = useState<Set<string>>(new Set());

  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [invLoading, setInvLoading] = useState(true);

  // Card expansion state per tab
  const [expandedCards, setExpandedCards] = useState<Set<string>>(new Set());
  const toggleCard = useCallback((id: string) => {
    setExpandedCards(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }, []);

  const toggleTrace = useCallback((orderId: string) => {
    setExpandedTraces(prev => {
      const next = new Set(prev);
      next.has(orderId) ? next.delete(orderId) : next.add(orderId);
      return next;
    });
  }, []);

  // Dedup guard for auto-invoice creation within a single session.
  // Prevents the same order from being processed twice across snapshot re-fires.
  const autoInvoicedRef = useRef<Set<string>>(new Set());

  const [refreshing, setRefreshing] = useState(false);
  const onRefresh = useCallback(() => {
    setRefreshing(true);
    setTimeout(() => setRefreshing(false), 600);
  }, []);

  // ── Auth guard (no early return — gated render below) ──────────────────────
  useEffect(() => {
    if (authLoading) return;
    if (!uid?.trim()) router.replace('/auth');
  }, [authLoading, uid, router]);

  // ── 1. Orders (ticket + non-custom service) ────────────────────────────────
  useEffect(() => {
    if (!uid) return;
    let cancelled = false;
    setOrdersLoading(true);

    const q = query(
      collection(db, 'orders'),
      where('clientId', '==', uid),
      orderBy('createdAt', 'desc'),
    );

    const unsub = onSnapshot(
      q,
      async (snap) => {
        if (cancelled) return;
        const raw: Order[] = snap.docs.map((dc) => {
          const d = dc.data() as any;
          const orderType = (d.orderType || 'ticket') as 'ticket' | 'service';
          const ticketItems = Array.isArray(d.ticketQuantities)
            ? d.ticketQuantities.map((qty: any) => ({
                name: qty.type || 'Ticket',
                qty: Number(qty.quantity || 0),
                price: Number(qty.price || 0),
              }))
            : undefined;

          return {
            id: dc.id,
            title:
              d.title ??
              d.serviceName ??
              (orderType === 'ticket' ? d.ticketName : undefined) ??
              'Order',
            description:
              d.description ??
              d.specialRequests ??
              d.message ??
              '',
            status: (d.status || d.orderStatus || 'pending') as OrderStatus,
            orderType,
            amount: Number(d.amount ?? d.totalPrice ?? d.clientPrice ?? 0),
            currency: d.currency || 'MAD',
            clientId: d.clientId,
            artistId: d.artistId,
            cover:
              d.cover ||
              d.image ||
              d.coverImage ||
              d.imageUrl ||
              d.serviceCover ||
              d.serviceImage ||
              d.thumbnail,
            items: Array.isArray(d.items) ? d.items : ticketItems,
            paymentStatus: d.paymentStatus,
            paymentMethod: d.paymentMethod,
            notes: d.notes,
            createdAt: normalizeDate(d.createdAt),
          };
        });

        const namesMap = await fetchArtistNames(
          db,
          raw.map(o => o.artistId).filter(Boolean) as string[],
        );
        const enriched = raw.map(o => ({
          ...o,
          artistName: o.artistId ? namesMap[o.artistId] : undefined,
        }));

        if (cancelled) return;
        setAllOrders(enriched);
        setOrdersLoading(false);

        // Auto-invoice any newly-confirmed orders.
        for (const o of enriched) {
          if (!INVOICE_TRIGGER_STATUSES.includes(o.status)) continue;
          if (autoInvoicedRef.current.has(o.id)) continue;
          autoInvoicedRef.current.add(o.id);
          ensureInvoiceForOrder(db, {
            orderId: o.id,
            orderType: o.orderType,
            userId: uid,
            amount: o.amount,
            currency: o.currency,
            artistName: o.artistName,
            title: o.title,
          }).catch(err => console.warn('auto-invoice (order) failed:', err));
        }
      },
      (err) => {
        if (cancelled) return;
        console.error('Error loading orders:', err);
        setOrdersLoading(false);
      },
    );

    return () => { cancelled = true; unsub(); };
  }, [uid, db]);

  // ── 2. Custom orders ───────────────────────────────────────────────────────
  useEffect(() => {
    if (!uid) return;
    let cancelled = false;
    setCustomOrdersLoading(true);

    const unsub = getClientCustomOrdersRealtime(
      uid,
      async (rawOrders: CustomOrderField[]) => {
        if (cancelled) return;
        const artistIds = [...new Set(rawOrders.map(o => o.artistId).filter(Boolean) as string[])];
        const namesMap = await fetchArtistNames(db, artistIds);

        const enriched: ServiceOrderWithMeta[] = rawOrders.map((o: any) => ({
          ...o,
          status: o.status || o.orderStatus || 'pending',
          createdAt: normalizeDate(o.createdAt),
          artistName: o.artistId ? namesMap[o.artistId] : undefined,
        }));

        if (cancelled) return;
        setClientCustomOrders(enriched);
        setCustomOrdersLoading(false);

        // Auto-invoice confirmed custom orders.
        for (const o of enriched) {
          const status = ((o as any).status || 'pending') as OrderStatus;
          if (!INVOICE_TRIGGER_STATUSES.includes(status)) continue;
          if (autoInvoicedRef.current.has(o.id)) continue;
          autoInvoicedRef.current.add(o.id);
          ensureInvoiceForOrder(db, {
            orderId: o.id,
            orderType: 'service',
            userId: uid,
            amount: Number((o as any).clientPrice ?? 0),
            currency: 'MAD',
            artistName: o.artistName,
            title: (o as any).serviceName || 'Service',
          }).catch(err => console.warn('auto-invoice (custom) failed:', err));
        }
      },
      (err) => {
        if (cancelled) return;
        console.error('Error loading custom orders:', err);
        setCustomOrdersLoading(false);
      },
    );

    return () => { cancelled = true; unsub(); };
  }, [uid, db]);

  // ── 3. Per-custom-order traceability ───────────────────────────────────────
  useEffect(() => {
    if (!uid || !clientCustomOrders.length) {
      setCustomOrderTraces({});
      return;
    }
    let cancelled = false;
    (async () => {
      const tracesMap: Record<string, TraceStep[]> = {};
      for (const co of clientCustomOrders) {
        try {
          tracesMap[co.id] = await getOrderTraceability(db, uid, co.id);
        } catch {
          tracesMap[co.id] = [];
        }
      }
      if (!cancelled) setCustomOrderTraces(tracesMap);
    })();
    return () => { cancelled = true; };
  }, [clientCustomOrders, uid, db]);

  // ── 4. Invoices ────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!uid) return;
    setInvLoading(true);

    const q = query(
      collection(db, 'invoices'),
      where('userId', '==', uid),
      orderBy('createdAt', 'desc'),
    );
    const unsub = onSnapshot(
      q,
      (snap) => {
        const data: Invoice[] = snap.docs.map((d) => {
          const x = d.data() as any;
          return {
            id: d.id,
            orderId: x.orderId,
            orderType: x.orderType || 'service',
            userId: x.userId,
            downloadURL: x.downloadURL,
            createdAt: normalizeDate(x.createdAt),
            amount: Number(x.amount ?? 0),
            currency: x.currency || 'MAD',
            status: x.status || 'issued',
            autoGenerated: !!x.autoGenerated,
            invoiceNumber: x.invoiceNumber,
            artistName: x.artistName,
            title: x.title,
          };
        });
        setInvoices(data);
        setInvLoading(false);
      },
      (err) => {
        console.error('Error loading invoices:', err);
        setInvLoading(false);
      },
    );
    return () => unsub();
  }, [uid, db]);

  // ── Delete handlers ────────────────────────────────────────────────────────
  const confirmDeleteOrder = useCallback((orderId: string, isCustom = false) => {
    Alert.alert(
      'Delete Order',
      'This action cannot be undone. Are you sure?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteDoc(doc(db, isCustom ? 'customOrders' : 'orders', orderId));
            } catch (err) {
              console.error('delete failed:', err);
              Alert.alert('Error', 'Unable to delete this order.');
            }
          },
        },
      ],
    );
  }, [db]);

  // ── Summary stats (derived) ───────────────────────────────────────────────
  const stats = useMemo(() => {
    const allItems = [
      ...allOrders.map(o => ({ amount: o.amount, status: o.status })),
      ...clientCustomOrders.map((o: any) => ({
        amount: Number(o.clientPrice ?? 0),
        status: (o.status || o.orderStatus || 'pending') as OrderStatus,
      })),
    ];
    const completedOrConfirmed = allItems.filter(i =>
      i.status === 'completed' || i.status === 'confirmed' || i.status === 'accepted',
    );
    return {
      totalSpent: completedOrConfirmed.reduce((s, i) => s + (i.amount || 0), 0),
      pendingCount: allItems.filter(i => i.status === 'pending').length,
      completedCount: completedOrConfirmed.length,
    };
  }, [allOrders, clientCustomOrders]);

  // ── Render ────────────────────────────────────────────────────────────────
  if (authLoading || !uid) {
    return (
      <View style={[styles.container, styles.loadingContainer]}>
        <ActivityIndicator size="large" color="#6366f1" />
        <Text style={styles.loadingText}>Loading…</Text>
      </View>
    );
  }

  const emptyState = (icon: string, title: string, body: string) => (
    <View style={styles.emptyContainer}>
      <Text style={styles.emptyIcon}>{icon}</Text>
      <Text style={styles.emptyTitle}>{title}</Text>
      <Text style={styles.emptyText}>{body}</Text>
    </View>
  );

  const tabs: Array<{ key: TabType; icon: keyof typeof Ionicons.glyphMap; label: string; count: number }> = [
    { key: 'orders', icon: 'cart-outline', label: 'Orders', count: allOrders.length },
    { key: 'custom', icon: 'construct-outline', label: 'Custom', count: clientCustomOrders.length },
    { key: 'invoices', icon: 'document-text-outline', label: 'Invoices', count: invoices.length },
  ];

  return (
    <View style={styles.container}>
      <SummaryHeader
        totalSpent={stats.totalSpent}
        pendingCount={stats.pendingCount}
        completedCount={stats.completedCount}
      />

      <View style={styles.tabRow}>
        {tabs.map(({ key, icon, label, count }) => {
          const focused = activeTab === key;
          return (
            <TouchableOpacity
              key={key}
              style={[styles.tabButton, focused && styles.tabButtonActive]}
              onPress={() => setActiveTab(key)}
              activeOpacity={0.8}
            >
              <Ionicons name={icon} size={15} color={focused ? '#fff' : '#6366f1'} />
              <Text style={[styles.tabLabel, focused && styles.tabLabelActive]}>
                {label}
              </Text>
              {count > 0 ? (
                <View style={[styles.tabBadge, focused && { backgroundColor: '#ffffff' }]}>
                  <Text style={[styles.tabBadgeText, focused && styles.tabBadgeTextActive]}>
                    {count}
                  </Text>
                </View>
              ) : null}
            </TouchableOpacity>
          );
        })}
      </View>

      {/* TAB: Orders */}
      {activeTab === 'orders' && (
        ordersLoading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color="#6366f1" />
            <Text style={styles.loadingText}>Loading orders…</Text>
          </View>
        ) : (
          <FlatList
            data={allOrders}
            keyExtractor={(item) => item.id}
            renderItem={({ item }) => (
              <OrderCard
                item={item}
                onDelete={() => confirmDeleteOrder(item.id)}
                expanded={expandedCards.has(item.id)}
                onToggleExpand={() => toggleCard(item.id)}
              />
            )}
            contentContainerStyle={styles.listContainer}
            showsVerticalScrollIndicator={false}
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#6366f1" />}
            ListEmptyComponent={emptyState(
              '📭',
              'No Orders Yet',
              'Your ticket and service orders will appear here once placed.',
            )}
          />
        )
      )}

      {/* TAB: Custom Orders */}
      {activeTab === 'custom' && (
        customOrdersLoading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color="#6366f1" />
            <Text style={styles.loadingText}>Loading custom orders…</Text>
          </View>
        ) : (
          <FlatList
            data={clientCustomOrders}
            keyExtractor={(item) => item.id}
            renderItem={({ item }) => (
              <CustomOrderCard
                item={item}
                traceSteps={customOrderTraces[item.id] || []}
                onToggleTrace={toggleTrace}
                onDelete={() => confirmDeleteOrder(item.id, true)}
                showTrace={expandedTraces.has(item.id)}
                expanded={expandedCards.has(item.id)}
                onToggleExpand={() => toggleCard(item.id)}
              />
            )}
            contentContainerStyle={styles.listContainer}
            showsVerticalScrollIndicator={false}
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#6366f1" />}
            ListEmptyComponent={emptyState(
              '📦',
              'No Custom Orders',
              'Custom service requests you place with artists will appear here with full traceability.',
            )}
          />
        )
      )}

      {/* TAB: Invoices */}
      {activeTab === 'invoices' && (
        invLoading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color="#6366f1" />
            <Text style={styles.loadingText}>Loading invoices…</Text>
          </View>
        ) : (
          <FlatList
            data={invoices}
            keyExtractor={(item) => item.id}
            renderItem={({ item }) => (
              <InvoiceItem
                item={item}
                expanded={expandedCards.has(item.id)}
                onToggleExpand={() => toggleCard(item.id)}
              />
            )}
            contentContainerStyle={styles.listContainer}
            showsVerticalScrollIndicator={false}
            refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#6366f1" />}
            ListEmptyComponent={emptyState(
              '🧾',
              'No Invoices Yet',
              'Invoices are generated automatically when an order is confirmed or completed.',
            )}
          />
        )
      )}
    </View>
  );
}